Repository Project-Agri-Portal/Cropify, pull requests merged in 2024-02, with the labels that each got.

#70 updated all the DTOs and SellerAgriProdService
  server/backend/src/main/java/com/cropify/dto/AdminDTO.java
  server/backend/src/main/java/com/cropify/dto/AgricultureProductsDTO.java
  server/backend/src/main/java/com/cropify/dto/CartAgricultureProductDTO.java
  server/backend/src/main/java/com/cropify/dto/CartFarmProductDTO.java
  server/backend/src/main/java/com/cropify/dto/CartMachineryDTO.java
  server/backend/src/main/java/com/cropify/dto/FarmerProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderAgricultureProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderFarmProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderMachineDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/SellerAgricultureProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/SellerMachineryDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/UserDetailsDTO.java
  server/backend/src/main/java/com/cropify/services/SellerAgricultureProductDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/SellerAgricultureProductDetailsServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/SellerMachineryDetailsServiceImpl.java
Labels: bug, enhancement

#74 Major DTO-level and method-level changes
  server/backend/src/main/java/com/cropify/controller/SellerAgricultureProductDetailsController.java
  server/backend/src/main/java/com/cropify/dao/SellerAgricultureProductDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/AgricultureProductsDTO.java
  server/backend/src/main/java/com/cropify/dto/SellerAgricultureProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/AgricultureProducts.java
  server/backend/src/main/java/com/cropify/entity/FarmProducts.java
  server/backend/src/main/java/com/cropify/entity/Machinery.java
  server/backend/src/main/java/com/cropify/entity/UserDetails.java
  server/backend/src/main/java/com/cropify/services/SellerAgricultureProductDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/SellerAgricultureProductDetailsServiceImpl.java
Labels: bug, documentation, enhancement

#75 fixed a issue of objects being set as null
  server/backend/src/main/java/com/cropify/controller/CartMachineryController.java
  server/backend/src/main/java/com/cropify/dto/AgricultureProductsDTO.java
  server/backend/src/main/java/com/cropify/dto/CartMachineryDTO.java
  server/backend/src/main/java/com/cropify/dto/MachineryDTO.java
  server/backend/src/main/java/com/cropify/dto/UserDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/CartMachinery.java
  server/backend/src/main/java/com/cropify/services/CartMachineryService.java
  server/backend/src/main/java/com/cropify/services/impl/CartMachineryServiceImpl.java
Labels: bug

#76 CRUD operations done
  server/backend/src/main/java/com/cropify/controller/SellerMachineryDetailsController.java
  server/backend/src/main/java/com/cropify/dao/SellerAgricultureProductDetailsRepository.java
  server/backend/src/main/java/com/cropify/dao/SellerMachineryDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/SellerMachineryDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/SellerMachineryDetails.java
  server/backend/src/main/java/com/cropify/services/SellerMachineryDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/SellerAgricultureProductDetailsServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/SellerMachineryDetailsServiceImpl.java
Labels: bug, enhancement

#77 Admin operations
  client/src/components/ComponentAdmin/Home.jsx
  client/src/components/ComponentAdmin/MainLayout.css
  client/src/components/ComponentsSeller/OrderList.jsx
  client/src/components/ComponentsSeller/Seller.css
  client/src/components/ComponentsSeller/SellerOrderList.css
  client/src/components/ComponentsSeller/SellerProducts.css
  client/src/components/Shop/ShopBody/Cart.jsx
  client/src/components/Shop/ShopBody/Contact.css
  client/src/components/Shop/ShopBody/ProductList.css
  client/src/components/Shop/ShopBody/ProductList.jsx
  server/backend/DummyData.sql
  server/backend/src/main/java/com/cropify/controller/AdminController.java
  server/backend/src/main/java/com/cropify/dao/AdminRepository.java
  server/backend/src/main/java/com/cropify/dto/AdminDTO.java
  server/backend/src/main/java/com/cropify/entity/Admin.java
  server/backend/src/main/java/com/cropify/services/AdminService.java
  server/backend/src/main/java/com/cropify/services/impl/AdminServiceImpl.java
Labels: enhancement

#79 Image operations and other fixes
  client/package-lock.json
  client/package.json
  client/src/assets/hero-section-bg-2.jpg
  client/src/components/ComponentAdmin/Home.jsx
  server/backend/src/main/java/com/cropify/controller/AgricultureProductsController.java
  server/backend/src/main/java/com/cropify/controller/FarmProductsController.java
  server/backend/src/main/java/com/cropify/dao/FarmProductsRepository.java
  server/backend/src/main/java/com/cropify/dto/FarmProductsDTO.java
  server/backend/src/main/java/com/cropify/dto/MachineryDTO.java
  server/backend/src/main/java/com/cropify/entity/AgricultureProducts.java
  server/backend/src/main/java/com/cropify/entity/FarmProducts.java
  server/backend/src/main/java/com/cropify/services/AgricultureProductsService.java
  server/backend/src/main/java/com/cropify/services/FarmProductsService.java
  server/backend/src/main/java/com/cropify/services/impl/AgricultureProudctsServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/FarmProductsServiceImpl.java
Labels: bug, enhancement

#82 Dev deepak
  server/backend/DummyData.sql
  server/backend/src/main/java/com/cropify/controller/MachineryController.java
  server/backend/src/main/java/com/cropify/controller/OrderMachineDetailsController.java
  server/backend/src/main/java/com/cropify/controller/UserDetailsController.java
  server/backend/src/main/java/com/cropify/dao/SellerMachineryDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/SellerMachineryDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/Machinery.java
  server/backend/src/main/java/com/cropify/entity/UserDetails.java
  server/backend/src/main/java/com/cropify/entity/enums/MachineType.java
  server/backend/src/main/java/com/cropify/services/MachineryService.java
  server/backend/src/main/java/com/cropify/services/UserDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/CartMachineryServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/MachineryServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/SellerMachineryDetailsServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/UserDetailsServiceImpl.java
Labels: bug

#83 Frontend and backend integration
  client/package-lock.json
  client/package.json
  client/src/components/UserAuthentication/SignIn/Login.jsx
  client/src/services/backend.service.js
  server/backend/src/main/java/com/cropify/controller/UserDetailsController.java
  server/backend/src/main/java/com/cropify/dao/UserDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/LoginDTO.java
  server/backend/src/main/java/com/cropify/dto/SellerMachineryDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/SellerMachineryDetails.java
  server/backend/src/main/java/com/cropify/services/UserDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/SellerMachineryDetailsServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/UserDetailsServiceImpl.java
Labels: enhancement

#84 Farm product Cart
  server/backend/src/main/java/com/cropify/controller/OrderFarmProductDetailsController.java
  server/backend/src/main/java/com/cropify/dao/CartFarmProductRepository.java
  server/backend/src/main/java/com/cropify/dao/OrderFarmProductDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/FarmerProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderAgricultureProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderFarmProductDetailsDTO.java
  server/backend/src/main/java/com/cropify/dto/OrderMachineDetailsDTO.java
  server/backend/src/main/java/com/cropify/entity/OrderAgricultureProductDetails.java
  server/backend/src/main/java/com/cropify/entity/OrderFarmProductDetails.java
  server/backend/src/main/java/com/cropify/services/OrderFarmProductDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/CartFarmerProductServiceImpl.java
  server/backend/src/main/java/com/cropify/services/impl/OrderFarmProductDetailsServiceImpl.java
Labels: documentation

#85 implemented user registration functionality through frontend
  client/src/components/UserAuthentication/SignIn/Login.jsx
  client/src/components/UserAuthentication/SignUp/Register.jsx
  client/src/services/login.service.js
Labels: enhancement

#87 Completed Product Page with all functionality
  client/package-lock.json
  client/package.json
  client/src/components/Shop/Common/NavBar.jsx
  client/src/components/Shop/ShopBody/MyService.jsx
  client/src/components/Shop/ShopBody/ProductList.css
  client/src/components/Shop/ShopBody/ProductList.jsx
  client/src/components/Shop/ShopBody/SpecialOffer.jsx
  client/src/services/shop.service.js
  server/backend/src/main/java/com/cropify/controller/FarmProductsController.java
  server/backend/src/main/java/com/cropify/controller/FarmerProductDetailsController.java
  server/backend/src/main/java/com/cropify/dao/FarmerProductDetailsRepository.java
  server/backend/src/main/java/com/cropify/dto/ShopDTO.java
  server/backend/src/main/java/com/cropify/services/FarmProductsService.java
  server/backend/src/main/java/com/cropify/services/FarmerProductDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/FarmerProductDetailsServiceImpl.java
Labels: documentation, enhancement

#89 Frontend enhancements and error fixes
  client/src/components/ComponentsSeller/SellerProfile.jsx
  client/src/components/ComponentsSeller/SellerProfileEdit.jsx
  client/src/components/UserAuthentication/SignIn/Login.jsx
  client/src/services/login.service.js
  client/src/services/seller.service.js
Labels: bug, enhancement

#103 Admin Complete
  client/src/App.js
  client/src/assets/WeacherAssets/clear.png
  client/src/assets/WeacherAssets/cloud.png
  client/src/assets/WeacherAssets/drizzle.png
  client/src/assets/WeacherAssets/humidity.png
  client/src/assets/WeacherAssets/rain.png
  client/src/assets/WeacherAssets/search.png
  client/src/assets/WeacherAssets/snow.png
  client/src/assets/WeacherAssets/wind.png
  client/src/components/ComponentAdmin/FarmerList.jsx
  client/src/components/ComponentAdmin/SellerList.jsx
  client/src/components/ComponentAdmin/SideBar.jsx
  client/src/components/ComponentsFarmer/FarmerCrops/WeatherAPI.css
  client/src/components/ComponentsFarmer/FarmerCrops/WeatherAPI.jsx
  client/src/components/Shop/ShopBody/HomeProduct.jsx
  client/src/components/Shop/ShopBody/Orders.jsx
  client/src/components/Shop/ShopBody/ProductList.jsx
  client/src/components/Shop/ShopBody/UserProfile.jsx
  client/src/components/Shop/ShopBody/Welcome.jsx
  client/src/components/Shop/ShopBody/style.css
  client/src/services/admin.service.js
  client/src/services/farmproduct.service.js
  client/src/services/shop.service.js
  client/src/services/user.service.js
  server/backend/src/main/java/com/cropify/controller/UserDetailsController.java
  server/backend/src/main/java/com/cropify/dao/FarmerProductDetailsRepository.java
  server/backend/src/main/java/com/cropify/dao/UserDetailsRepository.java
  server/backend/src/main/java/com/cropify/entity/FarmProducts.java
  server/backend/src/main/java/com/cropify/services/UserDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/UserDetailsServiceImpl.java
Labels: enhancement

#105 major file structure changes
  client/src/App.js
  client/src/components/ComponentsSeller/AddMachine.jsx
  client/src/components/ComponentsSeller/AddProduct.jsx
  client/src/components/ComponentsSeller/Dashboard.css
  client/src/components/ComponentsSeller/Dashboard.jsx
  client/src/components/ComponentsSeller/Seller.jsx
  client/src/components/ComponentsSeller/SellerMainPage.jsx
  client/src/components/ComponentsSeller/SellerOrderList.jsx
  client/src/components/ComponentsSeller/SellerProducts.jsx
  client/src/components/ComponentsSeller/SellerProfile.css
  client/src/components/ComponentsSeller/SellerProfile.jsx
  client/src/components/ComponentsSeller/SellerProfileEdit.jsx
  client/src/components/ComponentsSeller/sidebar.jsx
  client/src/components/UserAuthentication/SignIn/Login.jsx
  client/src/services/seller.service.js
  server/backend/src/main/java/com/cropify/controller/UserDetailsController.java
  server/backend/src/main/java/com/cropify/dao/UserDetailsRepository.java
  server/backend/src/main/java/com/cropify/services/UserDetailsService.java
  server/backend/src/main/java/com/cropify/services/impl/UserDetailsServiceImpl.java
Labels: bug, enhancement

#108 Payment API integration and various fixes
  client/public/index.html
  client/src/App.js
  client/src/assets/InfoImages/card-crops.jpg
  client/src/assets/InfoImages/card-machinery.jpg
  client/src/assets/InfoImages/card-vegetables.webp
  client/src/components/ComponentAdmin/AddProduct.jsx
  client/src/components/ComponentAdmin/SideBar.jsx
  client/src/components/ComponentsFarmer/AddProduct.jsx
  client/src/components/ComponentsFarmer/FarmerOrderList.jsx
  client/src/components/ComponentsSeller/AddMachine.jsx
  client/src/components/ComponentsSeller/SellerProfile.css
  client/src/components/HomePage/FarmerHome/FarmerHome.jsx
  client/src/components/Shop/ShopBody/Checkout.jsx
  client/src/components/Shop/ShopBody/ProductList.jsx
  client/src/components/Shop/ShopBody/style.css
  server/backend/DummyData.sql
  server/backend/src/main/java/com/cropify/entity/enums/MachineType.java
Labels: bug, enhancement
